/**
 * search/rag-search — RAG 检索增强生成搜索
 *
 * 流程：
 *   1. Agent 用 LLM 生成搜索关键词
 *   2. 调本工具，传入关键词列表
 *   3. 本工具：过滤语雀分词器不支持的符号（- . _）
 *   4. 并发调语雀搜索
 *   5. 按 doc_id 去重合并
 *   6. 获取前 N 篇文档的完整内容
 *   7. 返回搜索结果 + 文档内容，由 Agent 侧 LLM 总结
 *
 * 端点：复用 GET /api/v2/search + GET /api/v2/repos/docs/:id
 */

import type { McpTool } from "../common/types.js";
import {
  normalizeKeywords,
  searchYuque,
  fetchDoc,
  type SearchResult,
  type DocContent,
} from "./rag-search-utils.js";

// ─── Tool 定义 ────────────────────────────────────

export const searchRag: McpTool = {
  name: "yuque_rag_search",
  description: "RAG-enhanced search: accepts LLM-generated keywords, runs concurrent multi-path searches, deduplicates by doc_id, fetches top-N full doc content. 详见 references/api/search_api.md",
  inputSchema: {
    type: "object",
    properties: {
      keywords: {
        type: "string",
        description: "Search keywords, comma-separated. Generated by the calling LLM, 5-10 recommended",
      },
      scope: {
        type: "string",
        description: "Search scope, e.g. scope=group for team-only, or scope=group/book_slug for a repo. Leave empty for global",
      },
      creator: { type: "string", description: "Filter by author login" },
      max_results: {
        type: "number",
        description: "Max search results (default 10)",
      },
      fetch_docs: {
        type: "number",
        description: "Fetch full content of top N documents (default 3, max 5)",
      },
    },
    required: ["keywords"],
  },

  async handler(args) {
    const keywordsStr = args?.keywords as string;
    const scope = args?.scope as string | undefined;
    const creator = args?.creator as string | undefined;
    const maxResults = (args?.max_results as number) ?? 10;
    const fetchDocs = Math.min((args?.fetch_docs as number) ?? 3, 5);

    // 解析关键词
    const rawKeywords = keywordsStr
      .split(/[,，、\s]+/)
      .map((k) => k.trim())
      .filter(Boolean);

    if (rawKeywords.length === 0) {
      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify({
            meta: { total: 0, method: "rag_search", keywords_used: [] },
            data: [],
            docs: [],
          }, null, 2),
        }],
      };
    }

    // 过滤符号
    const keywords = normalizeKeywords(rawKeywords);

    // 并发多路搜索
    const allResults = await Promise.all(
      keywords.map((kw) => searchYuque(kw, scope, creator)),
    );

    // 按 doc_id 去重合并
    const seen = new Set<number>();
    const merged: SearchResult[] = [];
    for (const results of allResults) {
      for (const r of results) {
        if (!seen.has(r.doc_id)) {
          seen.add(r.doc_id);
          merged.push(r);
        }
      }
    }

    const finalResults = merged.slice(0, maxResults);

    // 获取前 N 篇文档的完整内容
    const docsToFetch = finalResults.slice(0, fetchDocs);
    const docs = (await Promise.all(
      docsToFetch.map((r) => fetchDoc(r.doc_id)),
    )).filter(Boolean) as DocContent[];

    return {
      content: [{
        type: "text" as const,
        text: JSON.stringify({
          meta: {
            total: finalResults.length,
            method: "rag_search",
            keywords_used: keywords,
            raw_keywords: rawKeywords,
            docs_fetched: docs.length,
          },
          data: finalResults,
          docs,
        }, null, 2),
      }],
    };
  },
};