/**
 * search/rag-search — RAG 检索增强生成搜索
 *
 * 流程：
 *   1. Agent 用 LLM 生成搜索关键词
 *   2. 调本工具，传入关键词列表
 *   3. 本工具：过滤语雀分词器不支持的符号（- . _）
 *   4. 并发调语雀搜索
 *   5. 按 doc_id 去重合并
 *   6. 获取前 N 篇文档的完整内容
 *   7. 返回搜索结果 + 文档内容，由 Agent 侧 LLM 总结
 *
 * 端点：复用 GET /api/v2/search + GET /api/v2/repos/docs/:id
 */

import type { McpTool } from "../common/types.js";
import { apiGet } from "../common/api-client.js";
import { isErrorResult } from "../common/api-client.js";
import { loadConfig } from "../common/config.js";

// ─── 关键词过滤 ──────────────────────────────────

/** 语雀分词器会切分的符号 */
const SPLIT_CHARS = /[-._]/;

/** 需要丢弃的纯符号 */
const STRIP_CHARS = /[\[\](){}<>【】「」『』""'']/g;

function normalizeKeywords(raw: string[]): string[] {
  const result: string[] = [];
  for (const kw of raw) {
    const trimmed = kw.trim();
    if (!trimmed) continue;

    const stripped = trimmed.replace(STRIP_CHARS, "").trim();
    if (!stripped) continue;

    if (SPLIT_CHARS.test(stripped)) {
      result.push(stripped.replace(SPLIT_CHARS, " "));
      result.push(stripped.replace(SPLIT_CHARS, ""));
    } else {
      result.push(stripped);
    }
  }
  return [...new Set(result)].slice(0, 10);
}

// ─── 语雀搜索 ────────────────────────────────────

interface SearchResult {
  id: number;
  doc_id: number;
  title: string;
  summary: string;
  url: string;
  book_name: string;
  book_slug: string;
  updated_at: string;
}

async function searchYuque(
  q: string,
  scope: string | undefined,
  creator: string | undefined,
): Promise<SearchResult[]> {
  const params: Record<string, string> = { q, type: "doc", page: "1" };
  if (scope) params.scope = scope;
  if (creator) params.creator = creator;

  const data = await apiGet("/search", params, `RAG search: ${q}`);
  if (isErrorResult(data)) return [];

  const typed = data as { data?: unknown[] };
  if (!typed?.data) return [];

  return typed.data.map((item: any) => ({
    id: item.id,
    doc_id: item.target?.id ?? item.id,
    title: item.title?.replace(/<em>|<\/em>/g, "") ?? "",
    summary: item.summary?.replace(/<em>|<\/em>/g, "") ?? "",
    url: item.url ?? "",
    book_name: item.target?.book?.name ?? "",
    book_slug: item.target?.book?.slug ?? "",
    updated_at: item.target?.content_updated_at ?? item.target?.updated_at ?? "",
  }));
}

// ─── 获取文档内容 ────────────────────────────────

interface DocContent {
  doc_id: number;
  title: string;
  body: string;
  url: string;
  book_name: string;
}

async function fetchDoc(
  docId: number,
): Promise<DocContent | null> {
  const data = await apiGet(`/repos/docs/${docId}`, undefined, `RAG fetch doc: ${docId}`);
  if (isErrorResult(data)) return null;

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const typed = data as { data?: Record<string, any> };
  const doc = typed?.data;
  if (!doc) return null;

  return {
    doc_id: docId,
    title: doc.title ?? "",
    body: doc.body ?? "",
    url: `https://www.yuque.com/${doc.book?.namespace ?? ""}/${doc.slug ?? ""}`,
    book_name: doc.book?.name ?? "",
  };
}

// ─── Tool 定义 ────────────────────────────────────

export const searchRag: McpTool = {
  name: "yuque_rag_search",
  description: "RAG-enhanced search: accepts LLM-generated keywords, runs concurrent multi-path searches, deduplicates by doc_id, fetches top-N full doc content. 详见 references/api/search_api.md",
  inputSchema: {
    type: "object",
    properties: {
      keywords: {
        type: "string",
        description: "Search keywords, comma-separated. Generated by the calling LLM, 5-10 recommended",
      },
      scope: {
        type: "string",
        description: "Search scope, e.g. scope=group for team-only, or scope=group/book_slug for a repo. Leave empty for global",
      },
      creator: { type: "string", description: "Filter by author login" },
      max_results: {
        type: "number",
        description: "Max search results (default 10)",
      },
      fetch_docs: {
        type: "number",
        description: "Fetch full content of top N documents (default 3, max 5)",
      },
    },
    required: ["keywords"],
  },

  async handler(args) {
    const cfg = loadConfig();
    const keywordsStr = args?.keywords as string;
    const scope = args?.scope as string | undefined;
    const creator = args?.creator as string | undefined;
    const maxResults = (args?.max_results as number) ?? 10;
    const fetchDocs = Math.min((args?.fetch_docs as number) ?? 3, 5);

    // 解析关键词
    const rawKeywords = keywordsStr
      .split(/[,，、\s]+/)
      .map((k) => k.trim())
      .filter(Boolean);

    if (rawKeywords.length === 0) {
      return {
        content: [{
          type: "text" as const,
          text: JSON.stringify({
            meta: { total: 0, method: "rag_search", keywords_used: [] },
            data: [],
            docs: [],
          }, null, 2),
        }],
      };
    }

    // 过滤符号
    const keywords = normalizeKeywords(rawKeywords);

    // 并发多路搜索
    const allResults = await Promise.all(
      keywords.map((kw) => searchYuque(kw, scope, creator)),
    );

    // 按 doc_id 去重合并
    const seen = new Set<number>();
    const merged: SearchResult[] = [];
    for (const results of allResults) {
      for (const r of results) {
        if (!seen.has(r.doc_id)) {
          seen.add(r.doc_id);
          merged.push(r);
        }
      }
    }

    const finalResults = merged.slice(0, maxResults);

    // 获取前 N 篇文档的完整内容
    const docsToFetch = finalResults.slice(0, fetchDocs);
    const docs = (await Promise.all(
      docsToFetch.map((r) => fetchDoc(r.doc_id)),
    )).filter(Boolean) as DocContent[];

    return {
      content: [{
        type: "text" as const,
        text: JSON.stringify({
          meta: {
            total: finalResults.length,
            method: "rag_search",
            keywords_used: keywords,
            raw_keywords: rawKeywords,
            docs_fetched: docs.length,
          },
          data: finalResults,
          docs,
        }, null, 2),
      }],
    };
  },
};